import {StoreWrapper} from '@/shared/lib/store/StoreWrapper';
import {Header} from '@/widgets/Header/Header';
import {GoogleOAuthProvider} from '@react-oauth/google';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';
import {Theme} from '@radix-ui/themes';
import {Toaster} from 'sonner';
import {AlertsProvider} from '@/shared/ui';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: {
    template: '%s | Inctagram',
    default: 'Inctagram',
  },
  description: "Generated by create next app",
  icons:{
    icon: '/favicon.ico',
  }
};

export default function RootLayout({children, modal}: Readonly<{children: React.ReactNode, modal: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
          <Theme appearance={'dark'}>
            <StoreWrapper>
                <AlertsProvider>
                  <Header notification={0} />
                  <main className={'main'}>
                    {children}
                    {modal}
                    <Toaster />
                  </main>
                </AlertsProvider>
            </StoreWrapper>
          </Theme>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
