import {StoreWrapper} from '@/shared/lib/store/StoreWrapper';
import {Header} from '@/widgets/Header/Header';
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import {Theme} from "@radix-ui/themes";
import {GoogleOAuthProvider} from "@react-oauth/google";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.variable}>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
            <Theme appearance={'dark'}>
                <StoreWrapper>
                    <Header isLogin={false} notification={0}/>
                    <main className={'main'}>
                        {children}
                    </main>
                </StoreWrapper>
            </Theme>
        </GoogleOAuthProvider>
        </body>
        </html>
    );
}
